# Database Configuration (Supabase)
spring.datasource.url=jdbc:postgresql://db.dtavtoysjqvyptvfmxxa.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=Pasindu18575@
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT Configuration
zephyratech.app.jwtSecret=zephyratechSecretKeyForJWTAuthGenerating256BitOrMoreLength
zephyratech.app.jwtExpirationMs=86400000

