# Database Configuration (SQLite)
spring.datasource.url=jdbc:sqlite:zephyratech.db
spring.datasource.driver-class-name=org.sqlite.JDBC

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.community.dialect.SQLiteDialect

# JWT Configuration
zephyratech.app.jwtSecret=${JWT_SECRET:zephyratechSecretKeyForJWTAuthGenerating256BitOrMoreLength}
zephyratech.app.jwtExpirationMs=86400000

